src/aspnetcoreapp1/Models/InsertProductViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using aspnetcoreapp1.Domains;

namespace aspnetcoreapp1.Models
{
    public class InsertProductViewModel
    {
        [Display(Prompt = "Enter Title")]
        [Required(ErrorMessage = "Title is required"), MaxLength(10, ErrorMessage = "Max length of title is 10 character")]
        public string Title { get; set; }

        public Category Category { get; set; }
        
        [Required(ErrorMessage = "Quantity is required"), Range(0, double.MaxValue, ErrorMessage = "Quantity must higher than 0")]
        public int Quantity { get; set; }

        [Display(Prompt = "Price")]
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Price is required"), Range(1, double.MaxValue, ErrorMessage = "Price must higher than 0")]
        public decimal Price { get; set; }
    }
}

src/aspnetcoreapp1/Models/Product.cs
using System;
using aspnetcoreapp1.Domains;

namespace aspnetcoreapp1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Category Category { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public DateTime Date { get; set; }
    }
}

src/aspnetcoreapp1/Models/ProductDetailsViewModel.cs
using System;

namespace aspnetcoreapp1.Models
{
    public class ProductDetailsViewModel : ProductViewModel
    {
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public DateTime Date { get; set; }
    }
}

src/aspnetcoreapp1/Models/ProductIndexViewModel.cs
using System.Collections.Generic;

namespace aspnetcoreapp1.Models
{
    public class ProductIndexViewModel
    {
        public IEnumerable<ProductViewModel> ProductViewModels { get; set; }
        public int TotalProductsAvailable { get; set; }
    }
}

src/aspnetcoreapp1/Models/ProductViewModel.cs
using aspnetcoreapp1.Domains;

namespace aspnetcoreapp1.Models
{
    public class ProductViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Category Category { get; set; }
    }
}

src/aspnetcoreapp1/Controllers/HomeController.cs
using aspnetcoreapp1.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace aspnetcoreapp1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IStringFormatter _stringFormatter;

        public HomeController(IStringFormatter stringFormatter)
        {
            _stringFormatter = stringFormatter;
        }

        public IActionResult Index()
        {
            ViewData["depMessage"] = _stringFormatter.FormatIt(new { Message = "Hello DI" });

            return View();
        }
    }
}

src/aspnetcoreapp1/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using aspnetcoreapp1.Models;
using aspnetcoreapp1.Services;
using Microsoft.AspNetCore.Mvc;

namespace aspnetcoreapp1.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            if (productService == null) throw new ArgumentNullException("Product service!");
            _productService = productService;
        }

        public IActionResult Index()
        {
            var productViewModels = GetAll();
            var productIndexViewModel = new ProductIndexViewModel
            {
                ProductViewModels = productViewModels,
                TotalProductsAvailable = productViewModels.Count()
            };
            return View(productIndexViewModel);
        }

        public IActionResult Detail(int id)
        {
            var productDetailsViewModel = new ProductDetailsViewModel();
            var product = _productService.GetBy(id);
            if (product != null)
            {
                productDetailsViewModel.Id = product.Id;
                productDetailsViewModel.Quantity = product.Quantity;
                productDetailsViewModel.Category = product.Category;
                productDetailsViewModel.Price = product.Price;
                productDetailsViewModel.Title = product.Title;
                productDetailsViewModel.Date = product.Date;
            }
            else
            {
                RedirectToAction("Index");
            }

            return View(productDetailsViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var insertProductViewModel = new InsertProductViewModel();
            return View(insertProductViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(InsertProductViewModel insertProductViewModel)
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Product()
                {
                    Title = insertProductViewModel.Title,
                    Category = insertProductViewModel.Category,
                    Date = DateTime.UtcNow,
                    Price = insertProductViewModel.Price,
                    Quantity = insertProductViewModel.Quantity
                };
                _productService.Add(newProduct);
                return RedirectToAction("Index");
            }

            return View();
        }

        private IEnumerable<ProductViewModel> GetAll()
        {
            var products = _productService.GetAll();
            return (from p in products select new ProductViewModel() { Id = p.Id, Category = p.Category, Title = p.Title});
        }
    }
}

src/aspnetcoreapp1/Views/Home/Index.cshtml
@{
}

<h2>aaa</h2>

src/aspnetcoreapp1/Views/Products/Create.cshtml
@model aspnetcoreapp1.Models.InsertProductViewModel

@{
    ViewBag.Title = "Insert new book";
}

<h1>Insert a new product</h1>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div>
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title)
    </div>
    <div>
        @Html.LabelFor(m => m.Quantity)
        @Html.TextBoxFor(m => m.Quantity)
    </div>
    <div>
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price)
    </div>
    <div>
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category, Html.GetEnumSelectList(typeof(aspnetcoreapp1.Domains.Category)))
    </div>
    <div>
        <input type="submit" name="create-product" value="Save" />
    </div>
}

src/aspnetcoreapp1/Views/Products/Detail.cshtml
@model aspnetcoreapp1.Models.ProductDetailsViewModel

@{
    ViewBag.Title = "Details of " + @Model.Title;
}

<h1>Details of @Model.Title</h1>

<table>
    <thead>
    <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Genre</th>
        <th>Pages</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.Title</td>
        <td>@Model.Category</td>
        <td>@Model.Quantity</td>
        <td>@Model.Price</td>
        <td>@Model.Date</td>
    </tr>
    </tbody>
</table>

@Html.ActionLink("Back to list", "Index", "Products")

src/aspnetcoreapp1/Views/Products/Index.cshtml
@model aspnetcoreapp1.Models.ProductIndexViewModel

@{
    ViewBag.Title = "Books";
}

<h1>Our products. In total: @Model.TotalProductsAvailable</h1>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Author</th>
        <th>Title</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var prouctViewModel in Model.ProductViewModels)
    {
        <tr>
            <td>@prouctViewModel.Id</td>
            <td>@prouctViewModel.Category</td>
            <td>@prouctViewModel.Title</td>
            <td>@Html.ActionLink("Detail", "Detail", "Products", new { id = prouctViewModel.Id })</td>
        </tr>
    }
    </tbody>
</table>
@*<a asp-action="deneme">Add new with tag library</a> tag helper*@

@section sectionexample {
    @Html.ActionLink("Add new Product", "Create")
}

src/aspnetcoreapp1/Views/Shared/_Layout.cshtml
@using aspnetcoreapp1.Helpers
@inject IStringFormatter StringFormatter

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <div>
        @RenderSection("sectionexample", false)
    </div>
    <div>
        <p>@StringFormatter.FormatIt(new { Message = "Dependency Injection into view" })</p>
    </div>
</body>
</html>